In [1]:
import pandas as pd

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
data=pd.read_csv("sample1.csv")
data.head()

Country  Age     Salary Purchased
0    India  40.0  100000.0       Yes
1   France  44.0   48000.0        No
2    Spain  50.0   50000.0       Yes
3  Germany  39.0       NaN        No
4    India  45.0  200000.0       Yes

In [7]:
x=data.iloc[:,:-1].values

In [11]:
print(x)

[['India' 40.0 100000.0]
 ['France' 44.0 48000.0]
 ['Spain' 50.0 50000.0]
 ['Germany' 39.0 nan]
 ['India' 45.0 200000.0]
 ['Spain' 35.0 80000.0]
 ['France' nan 40000.0]
 ['India' 30.0 90000.0]
 ['Germany' nan 20000.0]
 ['France' 40.0 nan]
 ['India' nan 50000.0]]


In [10]:
y=data.iloc[:,-1]
print(y)

0     Yes
1      No
2     Yes
3      No
4     Yes
5      No
6     Yes
7     Yes
8      No
9     Yes
10     No
Name: Purchased, dtype: object


In [13]:
pip install sklearn

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [14]:
from sklearn.impute import SimpleImputer

In [15]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')

In [16]:
imputer.fit(x[:,1:3])

SimpleImputer()

In [17]:
x[:,1:3]=imputer.transform(x[:,1:3])

In [18]:
x

array([['India', 40.0, 100000.0],
       ['France', 44.0, 48000.0],
       ['Spain', 50.0, 50000.0],
       ['Germany', 39.0, 75333.33333333333],
       ['India', 45.0, 200000.0],
       ['Spain', 35.0, 80000.0],
       ['France', 40.375, 40000.0],
       ['India', 30.0, 90000.0],
       ['Germany', 40.375, 20000.0],
       ['France', 40.0, 75333.33333333333],
       ['India', 40.375, 50000.0]], dtype=object)

In [21]:
pd.DataFrame(x)

0       1             2
0     India    40.0      100000.0
1    France    44.0       48000.0
2     Spain    50.0       50000.0
3   Germany    39.0  75333.333333
4     India    45.0      200000.0
5     Spain    35.0       80000.0
6    France  40.375       40000.0
7     India    30.0       90000.0
8   Germany  40.375       20000.0
9    France    40.0  75333.333333
10    India  40.375       50000.0

In [36]:
#one hot encoder
from sklearn.compose import ColumnTransformer

In [23]:
from sklearn.preprocessing import OneHotEncoder

In [24]:
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')

In [25]:
x=np.array(ct.fit_transform(x))

In [26]:
print(x)

[[0.0 0.0 1.0 0.0 40.0 100000.0]
 [1.0 0.0 0.0 0.0 44.0 48000.0]
 [0.0 0.0 0.0 1.0 50.0 50000.0]
 [0.0 1.0 0.0 0.0 39.0 75333.33333333333]
 [0.0 0.0 1.0 0.0 45.0 200000.0]
 [0.0 0.0 0.0 1.0 35.0 80000.0]
 [1.0 0.0 0.0 0.0 40.375 40000.0]
 [0.0 0.0 1.0 0.0 30.0 90000.0]
 [0.0 1.0 0.0 0.0 40.375 20000.0]
 [1.0 0.0 0.0 0.0 40.0 75333.33333333333]
 [0.0 0.0 1.0 0.0 40.375 50000.0]]


In [28]:
pd.DataFrame(x)

0    1    2    3       4             5
0   0.0  0.0  1.0  0.0    40.0      100000.0
1   1.0  0.0  0.0  0.0    44.0       48000.0
2   0.0  0.0  0.0  1.0    50.0       50000.0
3   0.0  1.0  0.0  0.0    39.0  75333.333333
4   0.0  0.0  1.0  0.0    45.0      200000.0
5   0.0  0.0  0.0  1.0    35.0       80000.0
6   1.0  0.0  0.0  0.0  40.375       40000.0
7   0.0  0.0  1.0  0.0    30.0       90000.0
8   0.0  1.0  0.0  0.0  40.375       20000.0
9   1.0  0.0  0.0  0.0    40.0  75333.333333
10  0.0  0.0  1.0  0.0  40.375       50000.0

In [29]:
#Label encoder

In [31]:
from sklearn.preprocessing import LabelEncoder

In [32]:
le=LabelEncoder()

In [33]:
y=le.fit_transform(y)

In [34]:
y

array([1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0])

In [35]:
print(y)

[1 0 1 0 1 0 1 1 0 1 0]


In [37]:
#splitting the dataset int0 the training and testing

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=1)

In [42]:
print(X_train)

[[1.0 0.0 0.0 0.0 40.375 40000.0]
 [0.0 0.0 1.0 0.0 40.0 100000.0]
 [0.0 0.0 1.0 0.0 30.0 90000.0]
 [0.0 0.0 1.0 0.0 40.375 50000.0]
 [0.0 1.0 0.0 0.0 40.375 20000.0]
 [0.0 0.0 0.0 1.0 35.0 80000.0]]


In [43]:
print(X_test)

[[0.0 0.0 0.0 1.0 50.0 50000.0]
 [0.0 1.0 0.0 0.0 39.0 75333.33333333333]
 [0.0 0.0 1.0 0.0 45.0 200000.0]
 [1.0 0.0 0.0 0.0 40.0 75333.33333333333]
 [1.0 0.0 0.0 0.0 44.0 48000.0]]


In [44]:
print(y_train)

[1 1 1 0 0 0]


In [45]:
print(y_test)

[1 0 1 1 0]
